export const Names = {
    'boys': {
      'A': [
        { 'name': 'Ahmed', 'meaning': 'Highly praised' },
        { 'name': 'Ali', 'meaning': 'Exalted, noble' },
        { 'name': 'Amir', 'meaning': 'Prince, commander' },
        { 'name': 'Ayaan', 'meaning': 'Gift of God' },
        { 'name': 'Adeel', 'meaning': 'Just, fair' },
        { 'name': 'Aariz', 'meaning': 'Respectable, leader' },
        { 'name': 'Arham', 'meaning': 'Most merciful' },
        { 'name': 'Aqeel', 'meaning': 'Wise, intelligent' },
        { 'name': 'Asad', 'meaning': 'Lion, courageous' },
        { 'name': 'Afnan', 'meaning': 'Branches, trees' },
      ],
      'B': [
        { 'name': 'Bilal', 'meaning': 'Moisture; name of a companion of the Prophet' },
        { 'name': 'Bashir', 'meaning': 'Bringer of good news' },
        { 'name': 'Badr', 'meaning': 'Full moon' },
        { 'name': 'Basim', 'meaning': 'Smiling' },
        { 'name': 'Burhan', 'meaning': 'Proof, evidence' },
        { 'name': 'Baleegh', 'meaning': 'Eloquent' },
        { 'name': 'Bashar', 'meaning': 'Bringer of glad tidings' },
        { 'name': 'Barak', 'meaning': 'Blessing' },
        { 'name': 'Badruddin', 'meaning': 'Full moon of the religion' },
        { 'name': 'Bahjat', 'meaning': 'Joy, delight' },
      ],
      'C': [
        { 'name': 'Cemal', 'meaning': 'Beauty, grace' },
        { 'name': 'Cihan', 'meaning': 'Universe, world' },
        { 'name': 'Cevdet', 'meaning': 'Excellence, goodness' },
        { 'name': 'Cavid', 'meaning': 'Eternal, immortal' },
        { 'name': 'Cemil', 'meaning': 'Handsome, graceful' },
        { 'name': 'Cengiz', 'meaning': 'Mighty, warrior' },
        { 'name': 'Ceyhun', 'meaning': 'A life-giving river' },
        { 'name': 'Celal', 'meaning': 'Majesty, grandeur' },
        { 'name': 'Can', 'meaning': 'Soul, life (Turkish variant)' },
        { 'name': 'Cihan', 'meaning': 'World (variant use)' },
      ],
      'D': [
        { 'name': 'Danish', 'meaning': 'Knowledge, wisdom' },
        { 'name': 'Dawood', 'meaning': 'Beloved; the Arabic form of David' },
        { 'name': 'Daniyal', 'meaning': 'Intelligent' },
        { 'name': 'Diyar', 'meaning': 'Gift' },
        { 'name': 'Dilshad', 'meaning': 'Happy heart' },
        { 'name': 'Daud', 'meaning': 'Beloved' },
        { 'name': 'Dastan', 'meaning': 'Legend, tale' },
        { 'name': 'Darakshan', 'meaning': 'Bright, shining' },
        { 'name': 'Duraid', 'meaning': 'Fighter (an old Arabic name)' },
        { 'name': 'Danyal', 'meaning': 'Variant of Daniyal' },
      ],
      'E': [
        { 'name': 'Ehsan', 'meaning': 'Perfection, excellence' },
        { 'name': 'Ebrahim', 'meaning': 'Father of nations; Arabic form of Abraham' },
        { 'name': 'Emad', 'meaning': 'Support, pillar' },
        { 'name': 'Ehab', 'meaning': 'Gift, donation' },
        { 'name': 'Elham', 'meaning': 'Inspiration' },
        { 'name': 'Emran', 'meaning': 'Prosperity' },
        { 'name': 'Eid', 'meaning': 'Festival, celebration' },
        { 'name': 'Elyas', 'meaning': "A prophet's name (Elijah)" },
        { 'name': 'Esam', 'meaning': 'Safeguard, security' },
        { 'name': 'Eshaq', 'meaning': 'Laughter; Arabic form of Isaac' },
      ],
      'F': [
        { 'name': 'Fahad', 'meaning': 'Panther; symbolizes speed and strength' },
        { 'name': 'Faisal', 'meaning': 'Decisive, arbitrator' },
        { 'name': 'Farhan', 'meaning': 'Joyful, happy' },
        { 'name': 'Fadi', 'meaning': 'Redeemer, savior' },
        { 'name': 'Faris', 'meaning': 'Knight, horseman' },
        { 'name': 'Fawaz', 'meaning': 'Successful, winner' },
        { 'name': 'Fikri', 'meaning': 'Intellectual, thoughtful' },
        { 'name': 'Fuad', 'meaning': 'Heart, soul' },
        { 'name': 'Fadil', 'meaning': 'Virtuous, generous' },
        { 'name': 'Fawwaz', 'meaning': 'Victorious' },
      ],
      'G': [
        { 'name': 'Ghazi', 'meaning': 'Warrior, conqueror' },
        { 'name': 'Ghalib', 'meaning': 'Victor, conqueror' },
        { 'name': 'Ghani', 'meaning': 'Wealthy, generous' },
        { 'name': 'Ghufran', 'meaning': 'Forgiveness' },
        { 'name': 'Ghaffar', 'meaning': 'Most forgiving' },
        { 'name': 'Ghaith', 'meaning': 'Rain, mercy' },
        { 'name': 'Ghazali', 'meaning': 'Of the Ghazala tribe; graceful' },
        { 'name': 'Ghazwan', 'meaning': 'Warrior' },
        { 'name': 'Ghazanfar', 'meaning': 'Lion' },
        { 'name': 'Ghulam', 'meaning': 'Servant, follower' },
      ],
      'H': [
        { 'name': 'Hasan', 'meaning': 'Handsome, good' },
        { 'name': 'Hussain', 'meaning': 'Small handsome one' },
        { 'name': 'Hamza', 'meaning': 'Lion, strong' },
        { 'name': 'Hadi', 'meaning': 'Guide, leader' },
        { 'name': 'Haris', 'meaning': 'Guardian, vigilant' },
        { 'name': 'Hisham', 'meaning': 'Generous, spirited' },
        { 'name': 'Hafiz', 'meaning': 'Guardian, memorizer (of the Quran)' },
        { 'name': 'Haider', 'meaning': 'Lion, brave' },
        { 'name': 'Humayun', 'meaning': 'Blessed, fortunate' },
        { 'name': 'Haseeb', 'meaning': 'Respected, noble' },
      ],
      'I': [
        { 'name': 'Ibrahim', 'meaning': 'Father of nations' },
        { 'name': 'Imran', 'meaning': 'Prosperity, populous' },
        { 'name': 'Ishaq', 'meaning': 'Laughter; Arabic form of Isaac' },
        { 'name': 'Ilyas', 'meaning': "A prophet's name (Elijah)" },
        { 'name': 'Idris', 'meaning': 'Interpreter, studious' },
        { 'name': 'Iqbal', 'meaning': 'Fortune, prosperity' },
        { 'name': 'Isa', 'meaning': 'Arabic form of Jesus' },
        { 'name': 'Ismail', 'meaning': 'God will hear' },
        { 'name': 'Irfan', 'meaning': 'Knowledge, awareness' },
        { 'name': 'Ijaz', 'meaning': 'Miracle, eloquence' },
      ],
      'J': [
        { 'name': 'Junaid', 'meaning': 'Warrior, soldier' },
        { 'name': 'Jalal', 'meaning': 'Majesty, glory' },
        { 'name': 'Javed', 'meaning': 'Eternal, immortal' },
        { 'name': 'Jibril', 'meaning': 'Gabriel; the archangel' },
        { 'name': 'Jamal', 'meaning': 'Beauty, grace' },
        { 'name': 'Jasim', 'meaning': 'Strong, handsome' },
        { 'name': 'Jahangir', 'meaning': 'Conqueror of the world' },
        { 'name': 'Jabir', 'meaning': 'Comforter, consoler' },
        { 'name': 'Jamil', 'meaning': 'Beautiful, graceful' },
        { 'name': 'Jamshed', 'meaning': 'Famous, radiant' },
      ],
      'K': [
        { 'name': 'Khalid', 'meaning': 'Eternal, immortal' },
        { 'name': 'Karim', 'meaning': 'Generous, noble' },
        { 'name': 'Kamal', 'meaning': 'Perfection, excellence' },
        { 'name': 'Khaleel', 'meaning': 'Friend, confidant' },
        { 'name': 'Kashif', 'meaning': 'Discoverer, revealer' },
        { 'name': 'Kamil', 'meaning': 'Perfect, complete' },
        { 'name': 'Kazim', 'meaning': 'Restrainer of anger' },
        { 'name': 'Khabir', 'meaning': 'Aware, knowledgeable' },
        { 'name': 'Khayyam', 'meaning': 'Tent maker; poetically refined' },
        { 'name': 'Khurram', 'meaning': 'Happy, delightful' },
      ],
      'L': [
        { 'name': 'Luqman', 'meaning': 'Wise, learned' },
        { 'name': 'Latif', 'meaning': 'Kind, gentle' },
        { 'name': 'Labeeb', 'meaning': 'Sensible, intelligent' },
        { 'name': 'Laith', 'meaning': 'Lion' },
        { 'name': 'Lutfi', 'meaning': 'Kind, friendly' },
        { 'name': 'Laarif', 'meaning': 'Knowledgeable (variant of Arif)' },
        { 'name': 'Lamaan', 'meaning': 'Soft, tender' },
        { 'name': 'Lafi', 'meaning': 'Gentle' },
        { 'name': 'Lubab', 'meaning': 'Essence, heart' },
        { 'name': 'Luqay', 'meaning': 'Small and clever' },
      ],
      'M': [
        { 'name': 'Muhammad', 'meaning': 'Praiseworthy' },
        { 'name': 'Musa', 'meaning': "Saved from the water; a prophet's name" },
        { 'name': 'Mahmood', 'meaning': 'Praised, commendable' },
        { 'name': 'Mansoor', 'meaning': 'Victorious' },
        { 'name': 'Mustafa', 'meaning': 'Chosen one' },
        { 'name': 'Murtaza', 'meaning': 'Chosen, accepted' },
        { 'name': 'Muawiyah', 'meaning': 'Young fox; leader' },
        { 'name': 'Mazin', 'meaning': 'Proper, cloud that carries rain' },
        { 'name': 'Moin', 'meaning': 'Helper, supporter' },
        { 'name': 'Mahir', 'meaning': 'Skilled, expert' },
      ],
      'N': [
        { 'name': 'Nabil', 'meaning': 'Noble' },
        { 'name': 'Naseer', 'meaning': 'Supporter, helper' },
        { 'name': 'Nadeem', 'meaning': 'Companion, friend' },
        { 'name': 'Naeem', 'meaning': 'Comfort, ease' },
        { 'name': 'Nadir', 'meaning': 'Rare, precious' },
        { 'name': 'Nouman', 'meaning': 'Bliss, comfort' },
        { 'name': 'Noman', 'meaning': 'Blessing' },
        { 'name': 'Najib', 'meaning': 'Noble, distinguished' },
        { 'name': 'Naim', 'meaning': 'Comfort, ease' },
        { 'name': 'Naser', 'meaning': 'Helper, supporter' },
      ],
      'O': [
        { 'name': 'Omar', 'meaning': 'Long-lived, flourishing' },
        { 'name': 'Othman', 'meaning': 'Old Arabic name; tender' },
        { 'name': 'Osama', 'meaning': 'Lion' },
        { 'name': 'Osman', 'meaning': 'Tender, chosen one' },
        { 'name': 'Owais', 'meaning': 'Little wolf' },
        { 'name': 'Omaid', 'meaning': 'Hope' },
        { 'name': 'Omran', 'meaning': 'Prosperity' },
        { 'name': 'Ovais', 'meaning': 'Variant of Owais' },
        { 'name': 'Omer', 'meaning': 'Variant of Omar' },
        { 'name': 'Ozir', 'meaning': 'Unique, rare' },
      ],
      'P': [
        { 'name': 'Parvez', 'meaning': 'Successful' },
        { 'name': 'Pervaiz', 'meaning': 'Victorious' },
        { 'name': 'Parsa', 'meaning': 'Pure' },
        { 'name': 'Pervez', 'meaning': 'Victorious' },
        { 'name': 'Paiman', 'meaning': 'Promise' },
        { 'name': 'Pashan', 'meaning': 'Rock, strong' },
        { 'name': 'Parid', 'meaning': 'Like a fairy' },
        { 'name': 'Parin', 'meaning': 'Complete, pure' },
        { 'name': 'Parman', 'meaning': 'Protector' },
        { 'name': 'Parviz', 'meaning': 'Fortunate' },
      ],
      'Q': [
        { 'name': 'Qasim', 'meaning': 'Distributor' },
        { 'name': 'Qudamah', 'meaning': 'Courageous' },
        { 'name': 'Qaiser', 'meaning': 'King' },
        { 'name': 'Qudrat', 'meaning': 'Power' },
        { 'name': 'Qurban', 'meaning': 'Sacrifice' },
        { 'name': 'Qadir', 'meaning': 'Capable, powerful' },
        { 'name': 'Qutb', 'meaning': 'Axis, pivot' },
        { 'name': 'Qayyum', 'meaning': 'Sustainer' },
        { 'name': 'Qamar', 'meaning': 'Moon' },
        { 'name': 'Qabil', 'meaning': 'Able, capable' },
      ],
      'R': [
        { 'name': 'Rahim', 'meaning': 'Compassionate' },
        { 'name': 'Raza', 'meaning': 'Contentment, satisfaction' },
        { 'name': 'Rauf', 'meaning': 'Kind, compassionate' },
        { 'name': 'Riaz', 'meaning': 'Grazing land; also means garden' },
        { 'name': 'Rashid', 'meaning': 'Rightly guided' },
        { 'name': 'Rami', 'meaning': 'Archer' },
        { 'name': 'Raheem', 'meaning': 'Merciful' },
        { 'name': 'Rifat', 'meaning': 'Exalted, high status' },
        { 'name': 'Rayan', 'meaning': 'Luxuriant, plentiful' },
        { 'name': 'Riazuddin', 'meaning': 'Gardener of the faith' },
      ],
      'S': [
        { 'name': 'Saad', 'meaning': 'Happiness, good fortune' },
        { 'name': 'Salman', 'meaning': 'Safe, secure' },
        { 'name': 'Shahid', 'meaning': 'Witness' },
        { 'name': 'Shakir', 'meaning': 'Thankful' },
        { 'name': 'Sami', 'meaning': 'Elevated, sublime' },
        { 'name': 'Suleiman', 'meaning': "Man of peace; a prophet's name" },
        { 'name': 'Shahzad', 'meaning': 'Prince, descendant of a king' },
        { 'name': 'Sadiq', 'meaning': 'Truthful' },
        { 'name': 'Shams', 'meaning': 'Sun' },
        { 'name': 'Sarfaraz', 'meaning': 'Honored, resplendent' },
      ],
      'T': [
        { 'name': 'Tariq', 'meaning': 'Morning star, pathfinder' },
        { 'name': 'Talha', 'meaning': 'A kind of tree; generous' },
        { 'name': 'Taimur', 'meaning': 'Iron' },
        { 'name': 'Taha', 'meaning': 'Pure, a letter of the Quran' },
        { 'name': 'Tahir', 'meaning': 'Pure, clean' },
        { 'name': 'Tayyab', 'meaning': 'Good-natured' },
        { 'name': 'Tufail', 'meaning': 'Companion' },
        { 'name': 'Tawfiq', 'meaning': 'Success, reconciliation' },
        { 'name': 'Tayyub', 'meaning': 'Patient; the name of a prophet' },
        { 'name': 'Tanzil', 'meaning': 'Revelation' },
      ],
      'U': [
        { 'name': 'Umar', 'meaning': 'Long-lived, flourishing' },
        { 'name': 'Usman', 'meaning': 'Tender, wise' },
        { 'name': 'Ubaid', 'meaning': 'Faithful, servant' },
        { 'name': 'Uthman', 'meaning': 'Old Arabic name' },
        { 'name': 'Ubaidullah', 'meaning': 'Servant of God' },
        { 'name': 'Umer', 'meaning': 'Variant of Umar' },
        { 'name': 'Uzair', 'meaning': 'Helper' },
        { 'name': 'Ubaidur', 'meaning': 'Servant of' },
        { 'name': 'Uvais', 'meaning': 'Little wolf' },
        { 'name': 'Uzzam', 'meaning': 'Respect, honor' },
      ],
      'V': [
        { 'name': 'Vaseem', 'meaning': 'Graceful, handsome' },
        { 'name': 'Vasim', 'meaning': 'Likeable' },
        { 'name': 'Vaseer', 'meaning': 'Elegant' },
        { 'name': 'Vadi', 'meaning': 'Prosperous' },
        { 'name': 'Vahid', 'meaning': 'Unique, singular' },
        { 'name': 'Vaqif', 'meaning': 'Observant' },
        { 'name': 'Vayyan', 'meaning': 'Full, abundant' },
        { 'name': 'Vali', 'meaning': 'Protector, guardian' },
        { 'name': 'Vizar', 'meaning': 'Bright, shining' },
        { 'name': 'Varen', 'meaning': 'Messenger' },
      ],
      'W': [
        { 'name': 'Waleed', 'meaning': 'Newborn' },
        { 'name': 'Walid', 'meaning': 'Newborn, eternal' },
        { 'name': 'Wajid', 'meaning': 'Lover, finder' },
        { 'name': 'Wasim', 'meaning': 'Handsome' },
        { 'name': 'Wali', 'meaning': 'Protector, friend' },
        { 'name': 'Waqas', 'meaning': 'Warrior' },
        { 'name': 'Waheed', 'meaning': 'Unique' },
        { 'name': 'Wasil', 'meaning': 'Connected' },
        { 'name': 'Waqaar', 'meaning': 'Dignity' },
        { 'name': 'Waliullah', 'meaning': 'Friend of God' },
      ],
      'X': [
        { 'name': 'Xaid', 'meaning': 'Leader (variant form)' },
        { 'name': 'Xamir', 'meaning': 'Brave' },
        { 'name': 'Xalif', 'meaning': 'Variant of Khalif (successor)' },
        { 'name': 'Xaleem', 'meaning': 'Gentle, forbearing' },
        { 'name': 'Xabir', 'meaning': 'Aware, knowledgeable' },
        { 'name': 'Xasim', 'meaning': 'Distributor (variant of Qasim)' },
        { 'name': 'Xadi', 'meaning': 'Helper' },
        { 'name': 'Xahil', 'meaning': 'Leader' },
        { 'name': 'Xazim', 'meaning': 'Resolute' },
        { 'name': 'Xaram', 'meaning': 'Honorable' },
      ],
      'Y': [
        { 'name': 'Yaseen', 'meaning': 'A chapter of the Quran' },
        { 'name': 'Yusuf', 'meaning': "God increases; a prophet's name" },
        { 'name': 'Yahya', 'meaning': 'Alive; Arabic form of John' },
        { 'name': 'Younis', 'meaning': "Dove; a prophet's name" },
        { 'name': 'Yasin', 'meaning': 'A chapter of the Quran' },
        { 'name': 'Yaqoob', 'meaning': 'Supplanter; Arabic form of Jacob' },
        { 'name': 'Yamin', 'meaning': 'Blessed, right-handed' },
        { 'name': 'Yaar', 'meaning': 'Friend' },
        { 'name': 'Yassar', 'meaning': 'Easy, soft' },
        { 'name': 'Yazeed', 'meaning': 'To increase' },
      ],
      'Z': [
        { 'name': 'Zaid', 'meaning': 'Abundance, growth' },
        { 'name': 'Zayn', 'meaning': 'Beauty, grace' },
        { 'name': 'Zakir', 'meaning': 'One who remembers (God)' },
        { 'name': 'Zaki', 'meaning': 'Pure, virtuous' },
        { 'name': 'Zubair', 'meaning': 'Strong, wise' },
        { 'name': 'Zahir', 'meaning': 'Shining, bright' },
        { 'name': 'Zakiuddin', 'meaning': 'Pure in faith' },
        { 'name': 'Zarar', 'meaning': 'Brave' },
        { 'name': 'Zayed', 'meaning': 'Abundance' },
        { 'name': 'Zarif', 'meaning': 'Witty, graceful' },
      ],
    },
    'girls': {
      'A': [
        { 'name': 'Amina', 'meaning': 'Trustworthy, faithful' },
        { 'name': 'Amira', 'meaning': 'Princess, leader' },
        { 'name': 'Ayesha', 'meaning': 'Alive, prosperous' },
        { 'name': 'Azra', 'meaning': 'Virgin, pure' },
        { 'name': 'Alia', 'meaning': 'Exalted, noble' },
        { 'name': 'Areeba', 'meaning': 'Wise, intelligent' },
        { 'name': 'Amani', 'meaning': 'Wishes, aspirations' },
        { 'name': 'Anisa', 'meaning': 'Friendly, companion' },
        { 'name': 'Ayat', 'meaning': 'Signs, verses (of the Quran)' },
        { 'name': 'Aabida', 'meaning': 'Devout, worshipper' },
      ],
      'B': [
        { 'name': 'Basma', 'meaning': 'Smile, cheerful' },
        { 'name': 'Bariha', 'meaning': 'Radiant, brilliant' },
        { 'name': 'Batool', 'meaning': 'Chaste; title for Lady Fatimah' },
        { 'name': 'Bashira', 'meaning': 'Bringer of good news' },
        { 'name': 'Barakah', 'meaning': 'Blessing, prosperity' },
        { 'name': 'Buthayna', 'meaning': 'Of a beautiful, tender body' },
        { 'name': 'Bushra', 'meaning': 'Good news, glad tidings' },
        { 'name': 'Badia', 'meaning': 'Unique, wonderful' },
        { 'name': 'Bisma', 'meaning': 'Grace, politeness' },
        { 'name': 'Balqis', 'meaning': 'Name of the Queen of Sheba' },
      ],
      'C': [
        { 'name': 'Camila', 'meaning': 'Perfection, noble' },
        { 'name': 'Clara', 'meaning': 'Bright, clear' },
        { 'name': 'Celine', 'meaning': 'Heavenly' },
        { 'name': 'Cyra', 'meaning': 'Moonlight, throne' },
        { 'name': 'Carmen', 'meaning': 'Garden, orchard' },
        { 'name': 'Calina', 'meaning': 'Tender, delicate' },
        { 'name': 'Celia', 'meaning': 'Heavenly' },
        { 'name': 'Chanda', 'meaning': 'Moonlight' },
        { 'name': 'Chazia', 'meaning': 'Young and graceful' },
        { 'name': 'Carima', 'meaning': 'Generous, noble' },
      ],
      'D': [
        { 'name': 'Dania', 'meaning': 'Close, near' },
        { 'name': 'Dina', 'meaning': 'Love, judge' },
        { 'name': 'Durrah', 'meaning': 'Pearl' },
        { 'name': 'Duaa', 'meaning': 'Supplication, prayer' },
        { 'name': 'Dalia', 'meaning': 'Gentle, slender branch' },
        { 'name': 'Diya', 'meaning': 'Light, glow' },
        { 'name': 'Dima', 'meaning': 'Downpour, cloudburst' },
        { 'name': 'Dalal', 'meaning': 'Coquetry, grace' },
        { 'name': 'Dareen', 'meaning': 'Precious, beautiful' },
        { 'name': 'Dana', 'meaning': 'Wise, knowledgeable' },
      ],
      'E': [
        { 'name': 'Emaan', 'meaning': 'Faith' },
        { 'name': 'Eman', 'meaning': 'Belief, faith' },
        { 'name': 'Esra', 'meaning': 'Journey of the night' },
        { 'name': 'Eila', 'meaning': 'Noble, radiant' },
        { 'name': 'Eimaan', 'meaning': 'Variant of faith' },
        { 'name': 'Eiliyah', 'meaning': 'Exalted, noble' },
        { 'name': 'Emani', 'meaning': 'Faithful' },
        { 'name': 'Elham', 'meaning': 'Inspiration' },
        { 'name': 'Eshal', 'meaning': 'Flower' },
        { 'name': 'Ezzah', 'meaning': 'Glory, honor' },
      ],
      'F': [
        { 'name': 'Fatima', 'meaning': 'Captivating; name of the Prophet’s daughter' },
        { 'name': 'Fariha', 'meaning': 'Happy, joyful' },
        { 'name': 'Farah', 'meaning': 'Joy, delight' },
        { 'name': 'Fawzia', 'meaning': 'Victorious' },
        { 'name': 'Fathima', 'meaning': 'Variant of Fatima' },
        { 'name': 'Fareeda', 'meaning': 'Unique, precious' },
        { 'name': 'Fizza', 'meaning': 'Sparkle, charm' },
        { 'name': 'Fariyal', 'meaning': 'Beautiful' },
        { 'name': 'Faria', 'meaning': 'Like a fairy' },
        { 'name': 'Fadwa', 'meaning': 'Self-sacrifice' },
      ],
      'G': [
        { 'name': 'Gulnaz', 'meaning': 'Delicate flower' },
        { 'name': 'Gulrukh', 'meaning': 'Face like a flower' },
        { 'name': 'Gulsan', 'meaning': 'Flower garden' },
        { 'name': 'Gulzar', 'meaning': 'Flower garden' },
        { 'name': 'Guley', 'meaning': 'Bloom, flower' },
        { 'name': 'Gulshan', 'meaning': 'Rose garden' },
        { 'name': 'Gulsima', 'meaning': 'Beautiful like a rose' },
        { 'name': 'Gulbadan', 'meaning': 'One with a delicate body' },
        { 'name': 'Gulee', 'meaning': 'Adorned with flowers' },
        { 'name': 'Gulchehra', 'meaning': 'Face like a flower' },
      ],
      'H': [
        { 'name': 'Hafsa', 'meaning': 'Gathering, young lioness' },
        { 'name': 'Huda', 'meaning': 'Guidance' },
        { 'name': 'Haniya', 'meaning': 'Happy, delighted' },
        { 'name': 'Hira', 'meaning': 'Diamond, a mountain' },
        { 'name': 'Humaira', 'meaning': 'Reddish, beautiful' },
        { 'name': 'Hina', 'meaning': 'Fragrance, Mehndi' },
        { 'name': 'Haseena', 'meaning': 'Beautiful' },
        { 'name': 'Hasna', 'meaning': 'Good, beautiful' },
        { 'name': 'Hareem', 'meaning': 'Sanctuary' },
        { 'name': 'Hidaya', 'meaning': 'Guidance' },
      ],
      'I': [
        { 'name': 'Imaan', 'meaning': 'Faith' },
        { 'name': 'Irum', 'meaning': 'Paradise' },
        { 'name': 'Inaya', 'meaning': 'Care, concern' },
        { 'name': 'Isra', 'meaning': 'Journey of the night' },
        { 'name': 'Ilma', 'meaning': 'Knowledge' },
        { 'name': 'Iqra', 'meaning': 'Read, recite' },
        { 'name': 'Iman', 'meaning': 'Faith, belief' },
        { 'name': 'Inaaya', 'meaning': 'Concern, solicitude' },
        { 'name': 'Ibtisam', 'meaning': 'Smile' },
        { 'name': 'Ishraq', 'meaning': 'Radiance, light' },
      ],
      'J': [
        { 'name': 'Jannat', 'meaning': 'Paradise' },
        { 'name': 'Jamila', 'meaning': 'Beautiful' },
        { 'name': 'Javeria', 'meaning': 'Bring happiness' },
        { 'name': 'Jumanah', 'meaning': 'Silver pearl' },
        { 'name': 'Jalila', 'meaning': 'Great, exalted' },
        { 'name': 'Jaleela', 'meaning': 'Majestic' },
        { 'name': 'Javerah', 'meaning': 'Variant of Javeria' },
        { 'name': 'Jinaan', 'meaning': 'Heart, soul' },
        { 'name': 'Jasmin', 'meaning': 'Fragrant flower' },
        { 'name': 'Jasmine', 'meaning': 'Flower' },
      ],
      'K': [
        { 'name': 'Khadija', 'meaning': 'Early baby; first wife of the Prophet' },
        { 'name': 'Komal', 'meaning': 'Delicate' },
        { 'name': 'Kiran', 'meaning': 'Ray of light' },
        { 'name': 'Karima', 'meaning': 'Noble, generous' },
        { 'name': 'Kainat', 'meaning': 'Universe' },
        { 'name': 'Kaniz', 'meaning': 'Servant, maid' },
        { 'name': 'Khairiya', 'meaning': 'Charitable' },
        { 'name': 'Kamilah', 'meaning': 'Perfect, complete' },
        { 'name': 'Kanza', 'meaning': 'Hidden treasure' },
        { 'name': 'Khadijah', 'meaning': 'Variant of Khadija' },
      ],
      'L': [
        { 'name': 'Laila', 'meaning': 'Night; dark beauty' },
        { 'name': 'Layla', 'meaning': 'Night; intoxication' },
        { 'name': 'Lubna', 'meaning': 'Elegant, storax tree' },
        { 'name': 'Leena', 'meaning': 'Tender, delicate' },
        { 'name': 'Liyana', 'meaning': 'Softness, tenderness' },
        { 'name': 'Lutfia', 'meaning': 'Kind, gentle' },
        { 'name': 'Lina', 'meaning': 'Tender, delicate' },
        { 'name': 'Labeeba', 'meaning': 'Sensible, intelligent' },
        { 'name': 'Laleh', 'meaning': 'Tulip' },
        { 'name': 'Lamis', 'meaning': 'Soft, tender' },
      ],
      'M': [
        { 'name': 'Maryam', 'meaning': 'Beloved; Arabic form of Miriam' },
        { 'name': 'Malika', 'meaning': 'Queen' },
        { 'name': 'Mahira', 'meaning': 'Skilled, expert' },
        { 'name': 'Meher', 'meaning': 'Light, sun' },
        { 'name': 'Munira', 'meaning': 'Luminous, radiant' },
        { 'name': 'Maira', 'meaning': 'Admirable' },
        { 'name': 'Mariam', 'meaning': 'Variant of Maryam' },
        { 'name': 'Mehreen', 'meaning': 'Bright, radiant' },
        { 'name': 'Madiha', 'meaning': 'Praiseworthy' },
        { 'name': 'Muskaan', 'meaning': 'Smile' },
      ],
      'N': [
        { 'name': 'Nida', 'meaning': 'Call, voice' },
        { 'name': 'Naima', 'meaning': 'Calm, tranquil' },
        { 'name': 'Nawal', 'meaning': 'Gift' },
        { 'name': 'Nadia', 'meaning': 'Moist, tender' },
        { 'name': 'Nargis', 'meaning': 'Narcissus (flower)' },
        { 'name': 'Noor', 'meaning': 'Light' },
        { 'name': 'Nura', 'meaning': 'Light' },
        { 'name': 'Nayyara', 'meaning': 'Radiant' },
        { 'name': 'Nazia', 'meaning': 'Proud, delicate' },
        { 'name': 'Nisma', 'meaning': 'Breeze' },
      ],
      'O': [
        { 'name': 'Omaira', 'meaning': 'Bright, luminous' },
        { 'name': 'Omera', 'meaning': 'Variant of Omaira' },
        { 'name': 'Orzala', 'meaning': 'Unique, rare' },
        { 'name': 'Orna', 'meaning': 'Light' },
        { 'name': 'Ozra', 'meaning': 'Radiance' },
        { 'name': 'Omaima', 'meaning': 'Little mother' },
        { 'name': 'Owaisah', 'meaning': 'Helper' },
        { 'name': 'Omina', 'meaning': 'Trust, belief' },
        { 'name': 'Olya', 'meaning': 'High, exalted' },
        { 'name': 'Omera', 'meaning': 'Repetition for emphasis' },
      ],
      'P': [
        { 'name': 'Parveen', 'meaning': 'Star' },
        { 'name': 'Parisa', 'meaning': 'Like a fairy' },
        { 'name': 'Pari', 'meaning': 'Fairy' },
        { 'name': 'Pakeezah', 'meaning': 'Pure' },
        { 'name': 'Parsa', 'meaning': 'Pious, pure' },
        { 'name': 'Parizaad', 'meaning': 'Born of a fairy' },
        { 'name': 'Parnaz', 'meaning': 'Delicate, tender' },
        { 'name': 'Parin', 'meaning': 'Complete, pure' },
        { 'name': 'Parine', 'meaning': 'Full, complete' },
        { 'name': 'Parvaizah', 'meaning': 'Successful' },
      ],
      'Q': [
        { 'name': 'Qamar', 'meaning': 'Moon' },
        { 'name': 'Qudsia', 'meaning': 'Holy, sacred' },
        { 'name': 'Qismah', 'meaning': 'Fate, destiny' },
        { 'name': 'Qisma', 'meaning': 'Portion, share' },
        { 'name': 'Quratulain', 'meaning': 'Delight of the eyes' },
        { 'name': 'Qistina', 'meaning': 'Just, fair' },
        { 'name': 'Qurat', 'meaning': 'Affection' },
        { 'name': 'Qarin', 'meaning': 'Companion' },
        { 'name': 'Qamarina', 'meaning': 'Moonlike' },
        { 'name': 'Qudrat', 'meaning': 'Power' },
      ],
      'R': [
        { 'name': 'Rabia', 'meaning': 'Spring, garden' },
        { 'name': 'Rania', 'meaning': 'Queenly, gazing' },
        { 'name': 'Rasha', 'meaning': 'Young gazelle' },
        { 'name': 'Razia', 'meaning': 'Content, satisfied' },
        { 'name': 'Rukhsar', 'meaning': 'Cheek, rosy' },
        { 'name': 'Rihana', 'meaning': 'Sweet basil' },
        { 'name': 'Rimsha', 'meaning': 'Bunch of flowers' },
        { 'name': 'Rida', 'meaning': 'Contentment' },
        { 'name': 'Rafia', 'meaning': 'Exalted' },
        { 'name': 'Rubina', 'meaning': 'Bright, shining' },
      ],
      'S': [
        { 'name': 'Sara', 'meaning': 'Pure, happy' },
        { 'name': 'Saira', 'meaning': 'Traveller' },
        { 'name': 'Sumaira', 'meaning': 'Dazzling' },
        { 'name': 'Sana', 'meaning': 'Brilliance, radiance' },
        { 'name': 'Shazia', 'meaning': 'Rare, unusual' },
        { 'name': 'Shaheen', 'meaning': 'Falcon' },
        { 'name': 'Saba', 'meaning': 'Morning breeze' },
        { 'name': 'Samira', 'meaning': 'Companion in evening talk' },
        { 'name': 'Salma', 'meaning': 'Safe, sound' },
        { 'name': 'Shabana', 'meaning': 'Night beauty' },
      ],
      'T': [
        { 'name': 'Tayyaba', 'meaning': 'Good-natured' },
        { 'name': 'Tahira', 'meaning': 'Pure, chaste' },
        { 'name': 'Tasmia', 'meaning': 'Recitation; beginning with Bismillah' },
        { 'name': 'Tasneem', 'meaning': 'A fountain in Paradise' },
        { 'name': 'Tania', 'meaning': 'Goddess, fairy queen' },
        { 'name': 'Tamana', 'meaning': 'Desire, wish' },
        { 'name': 'Tanveerah', 'meaning': 'Illuminating' },
        { 'name': 'Tarannum', 'meaning': 'Melody' },
        { 'name': 'Tazeen', 'meaning': 'Adornment' },
        { 'name': 'Tanzila', 'meaning': 'Revelation' },
      ],
      'U': [
        { 'name': 'Umm Aiman', 'meaning': 'Mother of Aiman; revered' },
        { 'name': 'Umm Kulthum', 'meaning': 'Name of the Prophet’s daughter' },
        { 'name': 'Ulfah', 'meaning': 'Affection, kindness' },
        { 'name': 'Urooj', 'meaning': 'Rise, ascent' },
        { 'name': 'Uzma', 'meaning': 'Greatest' },
        { 'name': 'Ulya', 'meaning': 'Exalted' },
        { 'name': 'Umaima', 'meaning': 'Little mother' },
        { 'name': 'Umme', 'meaning': 'Mother of' },
        { 'name': 'Uroosa', 'meaning': 'Bride' },
        { 'name': 'Ubaida', 'meaning': 'Faithful, servant' },
      ],
      'V': [
        { 'name': 'Vardah', 'meaning': 'Rose' },
        { 'name': 'Vania', 'meaning': 'Graceful' },
        { 'name': 'Varda', 'meaning': 'Rose' },
        { 'name': 'Vareesha', 'meaning': 'Shining' },
        { 'name': 'Varisha', 'meaning': 'Rain' },
        { 'name': 'Vasmia', 'meaning': 'Variant denoting beauty' },
        { 'name': 'Vahida', 'meaning': 'Unique' },
        { 'name': 'Vaniaa', 'meaning': 'Graceful variant' },
        { 'name': 'Varez', 'meaning': 'Bright' },
        { 'name': 'Viyana', 'meaning': 'Lively' },
      ],
      'W': [
        { 'name': 'Wafa', 'meaning': 'Loyalty' },
        { 'name': 'Warda', 'meaning': 'Rose' },
        { 'name': 'Widad', 'meaning': 'Affection, love' },
        { 'name': 'Wafaa', 'meaning': 'Loyalty, faithfulness' },
        { 'name': 'Waniya', 'meaning': 'Desirable' },
        { 'name': 'Wasima', 'meaning': 'Graceful, beautiful' },
        { 'name': 'Waseema', 'meaning': 'Beautiful' },
        { 'name': 'Wardah', 'meaning': 'Rose' },
        { 'name': 'Wafiya', 'meaning': 'Faithful' },
        { 'name': 'Waliyah', 'meaning': 'Protector' },
      ],
      'X': [
        { 'name': 'Xena', 'meaning': 'Guest, stranger' },
        { 'name': 'Xara', 'meaning': 'Shining' },
        { 'name': 'Xamira', 'meaning': 'Brave' },
        { 'name': 'Xaliyah', 'meaning': 'Exalted' },
        { 'name': 'Xafira', 'meaning': 'Forgiving' },
        { 'name': 'Xane', 'meaning': 'Variant of Zain' },
        { 'name': 'Xalia', 'meaning': 'Graceful' },
        { 'name': 'Xaria', 'meaning': 'Princess' },
        { 'name': 'Xayla', 'meaning': 'Beautiful' },
        { 'name': 'Xyla', 'meaning': 'Woodland; strong' },
      ],
      'Y': [
        { 'name': 'Yusra', 'meaning': 'Ease, comfort' },
        { 'name': 'Yasmin', 'meaning': 'Jasmine flower' },
        { 'name': 'Yara', 'meaning': 'Small butterfly' },
        { 'name': 'Yamina', 'meaning': 'Right-handed, blessed' },
        { 'name': 'Yumna', 'meaning': 'Fortunate' },
        { 'name': 'Yaquta', 'meaning': 'Ruby' },
        { 'name': 'Yusrah', 'meaning': 'Ease, prosperity' },
        { 'name': 'Yaseena', 'meaning': 'A chapter in the Quran' },
        { 'name': 'Yosra', 'meaning': 'Ease, comfort' },
        { 'name': 'Yaminah', 'meaning': 'Blessed' },
      ],
      'Z': [
        { 'name': 'Zainab', 'meaning': 'Father’s precious jewel' },
        { 'name': 'Zahra', 'meaning': 'Radiant, luminous' },
        { 'name': 'Zoya', 'meaning': 'Alive, blossoming' },
        { 'name': 'Zain', 'meaning': 'Beauty, grace' },
        { 'name': 'Zakia', 'meaning': 'Pure, intelligent' },
        { 'name': 'Zubaida', 'meaning': 'Elite, brilliant' },
        { 'name': 'Zulekha', 'meaning': 'Brilliant, intelligent' },
        { 'name': 'Zamzam', 'meaning': 'Holy water' },
        { 'name': 'Zara', 'meaning': 'Princess, flower' },
        { 'name': 'Zarina', 'meaning': 'Golden' },
      ],
    },
  };
